# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.supportedFilesystems = [ "btrfs" ];
  #boot.initrd.kernelModules = ["pinctrl_tigerlake"];
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.postDeviceCommands = lib.mkAfter ''
    mkdir /mnt
    mount -t btrfs /dev/mapper/cry /mnt
    btrfs subvolume delete /mnt/@
    btrfs subvolume snapshot /mnt/@snapshot /mnt/@
  '';

  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.resumeDevice = "/dev/disk/by-uuid/0f0a5969-bf7c-4655-80d9-a884fe457508";
  #boot.resumeDevice = "/dev/mapper/cry";
  boot.kernelParams = [
    "resume_offset=533760"
    "mem_sleep_default=deep"
  ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/0f0a5969-bf7c-4655-80d9-a884fe457508";
    fsType = "btrfs";
    options = [
      "subvol=@"
      "noatime"
      "space_cache=v2"
      "compress=zstd"
      "discard=async"
      "ssd"
    ];
  };

  boot.initrd.luks.devices."cry".device = "/dev/disk/by-uuid/f78891f2-2559-4c21-b570-63cfd4e9a046";

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/0f0a5969-bf7c-4655-80d9-a884fe457508";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "noatime"
      "space_cache=v2"
      "compress=zstd"
      "discard=async"
      "ssd"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/0f0a5969-bf7c-4655-80d9-a884fe457508";
    fsType = "btrfs";
    options = [
      "subvol=@nix"
      "noatime"
      "space_cache=v2"
      "compress=zstd"
      "discard=async"
      "ssd"
    ];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/0f0a5969-bf7c-4655-80d9-a884fe457508";
    fsType = "btrfs";
    options = [
      "subvol=@persist"
      "noatime"
      "space_cache=v2"
      "compress=zstd"
      "discard=async"
      "ssd"
    ];
  };

  fileSystems."/var/log" = {
    device = "/dev/disk/by-uuid/0f0a5969-bf7c-4655-80d9-a884fe457508";
    fsType = "btrfs";
    options = [
      "subvol=@log"
      "noatime"
      "space_cache=v2"
      "compress=zstd"
      "discard=async"
      "ssd"
    ];
  };

  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/0f0a5969-bf7c-4655-80d9-a884fe457508";
    fsType = "btrfs";
    options = [
      "subvol=@swap"
      "noatime"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/12CE-A600";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [
    {
      device = "/swap/swapfile";
    }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s13f0u1c2.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
