# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.initrd.postDeviceCommands = lib.mkAfter ''
	mkdir /mnt
	mount -t btrfs /dev/mapper/enc /mnt
	btrfs subvolume delete /mnt/root
	btrfs subvolume snapshot /mnt/root-blank /mnt/root
  	'';
  boot.supportedFilesystems = ["btrfs"];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.resumeDevice = "/dev/disk/by-uuid/71afaa19-49ce-4540-8d2a-a92c4ea1246e";
  boot.kernelParams = ["resume_offset=533760"];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/71afaa19-49ce-4540-8d2a-a92c4ea1246e";
      fsType = "btrfs";
      options = [ "subvol=root" "noatime" "ssd" "space_cache=v2" "discard=async" "compress=zstd"];
    };

  boot.initrd.luks.devices."enc".device = "/dev/disk/by-uuid/7d1aa661-0994-4544-8e5f-b1db039af549";

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/71afaa19-49ce-4540-8d2a-a92c4ea1246e";
      fsType = "btrfs";
      options = [ "subvol=home" "noatime" "ssd" "space_cache=v2" "discard=async" "compress=zstd"];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/71afaa19-49ce-4540-8d2a-a92c4ea1246e";
      fsType = "btrfs";
      options = [ "subvol=nix" "noatime" "ssd" "space_cache=v2" "discard=async" "compress=zstd"];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/71afaa19-49ce-4540-8d2a-a92c4ea1246e";
      fsType = "btrfs";
      options = [ "subvol=persist" "noatime" "ssd" "space_cache=v2" "discard=async" "compress=zstd"];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/71afaa19-49ce-4540-8d2a-a92c4ea1246e";
      fsType = "btrfs";
      options = [ "subvol=log" "noatime" "ssd" "space_cache=v2" "discard=async" "compress=zstd"];
	neededForBoot = true;
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/71afaa19-49ce-4540-8d2a-a92c4ea1246e";
      fsType = "btrfs";
      options = [ "subvol=swap" "noatime"];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/12CE-A600";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ {device = "/swap/swapfile";} ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
